### ISSUE TITLE
Dependency information mention

### ISSUE THREAD

**Issue by catskul** [insin/newforms-bootstrap#2]
This is probably moot if using npm, but relevant otherwise.

The library has a few dependencies that should probably be called out in the readme. The one that caught me was `react-with-addons-0.12.2.min.js` as I'd been using `react-0.12.2.js` and getting errors.

(Awesome library by the way!)

**Comment by insin** [comment]
Will do, thanks for the report.

This requirement will go away with React 0.13 as it brings `React.cloneElement` to the top-level API. The current cloning approach should go away entirely when facebook/react#2112 lands.
